<a href="https://colab.research.google.com/github/mahekgheewala/Heart_Project/blob/main/Heart_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

In [3]:
# Importing Libraries
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [4]:
heart_data = pd.read_csv('/content/heart.csv')

In [5]:
heart_data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [6]:
heart_data.shape

(1025, 14)

In [7]:
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [9]:
# Splitting the Data
X = heart_data.drop(columns=['target'], axis = 1)
Y = heart_data['target']

In [10]:
print(X)

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  
0         2   2     3  
1         0   0     3  
2  

In [11]:
print(Y)

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64


In [19]:
# Standardizing the Data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_fit = scaler.fit_transform(X)

In [24]:
# Loading the models
models = [LogisticRegression(max_iter=2000), KNeighborsClassifier(), SVC(kernel='linear')]

In [25]:
# Function to compare models
def cross_validation_models():
  for model in models:
    cv_score = cross_val_score(model, X, Y, cv=5)
    print(cv_score)
    mean_accuracy = sum(cv_score)/len(cv_score)
    mean_accuracy = mean_accuracy * 100
    mean_accuracy = round(mean_accuracy, 2)
    print(mean_accuracy, model)

In [26]:
cross_validation_models()

[0.88292683 0.85853659 0.87804878 0.82439024 0.80487805]
84.98 LogisticRegression(max_iter=2000)
[0.76585366 0.74634146 0.76097561 0.71219512 0.75121951]
74.73 KNeighborsClassifier()
[0.88292683 0.86829268 0.84390244 0.81463415 0.80487805]
84.29 SVC(kernel='linear')


In [27]:
# Selecting the best Model:
best_model = LogisticRegression(max_iter=2000)
best_model.fit(X,Y)

LogisticRegression(max_iter=2000)

In [29]:
# Saving thr model
import pickle

In [33]:
file_name = 'heart_data.sav'
pickle.dump(best_model, open(file_name, 'wb'))

In [34]:
# Loading the saved model
loaded_model = pickle.load(open('heart_data.sav', 'rb'))